title: Alex Young

nav:
    - title: Home
      href: /
    - title: About
      href: /about

links:
    - href: https://www.instagram.com/alexpyoung
      src: /assets/instagram.svg
    - href: https://www.linkedin.com/in/alexphillipyoung
      src: /assets/linkedin.svg
    - href: https://github.com/alexpyoung
      src: /assets/github.svg
    - href: mailto:alexphillipyoung@gmail.com
      src: /assets/email.svg

photos:
    - /assets/photos/HalfDome1.jpg
    - /assets/photos/LimekilnCreekBridge.jpg
    - /assets/photos/Brian.jpg
    - /assets/photos/JudasTree.jpg
    - /assets/photos/NanLien.jpg
    - /assets/photos/WTC.JPG
    - /assets/photos/HalfDome0.jpg
    - /assets/photos/Malecon.jpg
    - /assets/photos/Sarah.jpg
    - /assets/photos/Roscoe.jpg
    - /assets/photos/KipsBay.jpg
    - /assets/photos/Bee.jpg
    - /assets/photos/Trinidad.jpg
    - /assets/photos/Rain.jpg
    - /assets/photos/PfiefferBeach.jpg
    - /assets/photos/Matt.jpg
    - /assets/photos/PuentedeBacunayagua.jpg

markdown: kramdown
theme: minima
sass:
    sass_dir: styles
    style: compressed
